Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult ContactPage()
        {
            return View();
        }
    }
}

Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;
using Web.Models;

namespace Web.Controllers
{
    public class SearchController : Controller
    {
        UserRepository rep = new UserRepository();

        [HttpGet]
        public ActionResult Search()
        {
            string userName = System.Web.HttpContext.Current.User.Identity.Name;
            int userID = UserRepository.GetUserId(userName);


            return PartialView("_SearchFormPartial");
        }

        [HttpPost]
        public ActionResult Search(string hotelName)
        {
            if (hotelName != null)
            {
                try
                {
                    var searchlist = rep.GetSearchedHotels(hotelName);

                    var model = new SearchModel()
                    {
                        Hotels = searchlist
                    };

                    string currUser = System.Web.HttpContext.Current.User.Identity.Name;
                    int userID = UserRepository.GetUserId(currUser);


                    return PartialView("_SearchResultsPartial", model);
                }
                catch (Exception e)
                {
                    throw e;
                }
            }
            return PartialView("Error");
        }
    }
}

Web/Views/Shared/UploadImage.cshtml
@ViewBag.Message

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ProjectX</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="@Url.Content("/Scripts/jquery-1.12.4.js")"></script>
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery.validate.js")"></script>
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery.validate.unobtrusive.js")"></script>
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery-ui-1.12.1.js")"></script>

    @RenderSection("JavaScript", required: false)
    @RenderSection("Styles", false)

</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {

        <div class="navbar-collapse collapse">
            <ul class="nav nav-tabs">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                    &nbsp;&nbsp;
                </li>
                <li>
                    @Html.ActionLink("My Profile", "UserProfile", "UserProfile")
                    &nbsp;&nbsp;
                </li>
                <li>
                    @Html.ActionLink("Log out", "LogOut", "Account")
                    &nbsp;&nbsp;
                </li>
                <li>
                    @Html.ActionLink("Contact us", "ContactPage", "Contact")
                    &nbsp;&nbsp;
                </li>
                <li>  @Html.ActionLink("Search hotel", "Search", "Search")
                </li>
</ul>
        </div>
    }
    else
    {

        <div class="navbar-collapse collapse">
            <ul class="nav nav-tabs">
                <li> @Html.ActionLink("Home", "Index", "Home")</li>
                &nbsp;&nbsp;
                <li>
                    @Html.ActionLink("Sign in", "Login", "Account")
                    &nbsp;&nbsp;
                </li>
                <li>
                    @Html.ActionLink("Create an account", "CreateUser", "Account")
                    &nbsp;&nbsp;
                </li>
                <li>
                    @Html.ActionLink("Contact us", "ContactPage", "Contact")
                </li>
            </ul>
        </div>

    }

    @RenderBody()
</body>

</html>

Web/Views/Shared/_ReservationSearchPartial.cshtml
@model Web.Models.ReservationModel


    <div class="container" style="background-color:#cfcfcf; border-radius: 25px; padding-bottom: 1cm;">
        <h3>Sök efter ledigt rum</h3>
        <p>Incheckning: </p>
        @Html.TextBoxFor(model => model.Check_In, new { @class = "form-control", @id = "TextBox1" })
        <p>Utcheckning: </p>
        @Html.TextBoxFor(model => model.Check_Out, new { @class = "form-control", @id = "TextBox2" })

        <label>Antal nätter: </label> <label type="text" id="TextBox3"></label>
        <br />
        <input type="submit" value="Sök" class="btn btn-default" />
    </div>

<script>
    $("#TextBox1").datepicker({
        minDate: 0,
        maxDate: '+1Y+6M',
        onSelect: function (dateStr) {
            var min = $(this).datepicker('getDate'); // Get selected date
            $("#TextBox2").datepicker('option', 'minDate', min || '0'); // Set other min, default to today
        }
    });

    $("#TextBox2").datepicker({
        minDate: '0',
        maxDate: '+1Y+6M',
        onSelect: function (dateStr) {
            var max = $(this).datepicker('getDate'); // Get selected date
            $('#datepicker').datepicker('option', 'maxDate', max || '+1Y+6M'); // Set other max, default to +18 months
            var start = $("#TextBox1").datepicker("getDate");
            var end = $("#TextBox2").datepicker("getDate");
            var days = (end - start) / (1000 * 60 * 60 * 24);
            $("#TextBox3").text(days);
        }
    });
</script>

Web/Views/Shared/_SearchFormPartial.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("Search", "Search", FormMethod.Post,
        new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "POST",
            UpdateTargetId = "search-results"
        }))
{
    <div>
        @Html.TextBox("hotelName")
        <input type="submit" value="Search" />
    </div>
}

Web/Views/Shared/_SearchResultsPartial.cshtml
@model Web.Models.SearchModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="loginForm">
    <h2>Search results!</h2>
    <br />
    @if (Model.Hotels.Count == 0)
    {
        <h3 class="text-error">No items matched your search query!</h3>
    }
    else
    {
        foreach (var result in Model.Hotels)
        {
            <a href='@(Url.Action("HotelInfo", "HotelInfo", new { hotelHID = @result.HID }))'>
                @result.Hotelname  &nbsp;@result.City &nbsp;@result.Country
            </a>
    <br />
        }
    }
</div>